import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Vocabulary from '../models/Vocabulary.js';

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await User.deleteMany({});
    await Vocabulary.deleteMany({});
    console.log('✅ Cleared existing data');

    const teacher = await User.create({
      name: 'Ms. Kim',
      email: 'teacher@classcard.com',
      password: 'password123',
      role: 'teacher'
    });
    console.log('✅ Teacher created:', teacher.email);

    const student = await User.create({
      name: 'Minho Lee',
      email: 'student@classcard.com',
      password: 'password123',
      role: 'student',
      class: 'Class A',
      section: 'Beginner',
      teacherId: teacher._id
    });
    console.log('✅ Student created:', student.email);
     const vocabulary =  [
  // 🟢 1. Beginner (easy words) - 100 words
  { word: 'apple', meaning: '사과', example: 'I eat an apple every day.', level: 'Beginner' },
  { word: 'book', meaning: '책', example: 'I read a book.', level: 'Beginner' },
  { word: 'dog', meaning: '개', example: 'The dog is cute.', level: 'Beginner' },
  { word: 'cat', meaning: '고양이', example: 'The cat sleeps.', level: 'Beginner' },
  { word: 'water', meaning: '물', example: 'I drink water.', level: 'Beginner' },
  { word: 'school', meaning: '학교', example: 'I go to school.', level: 'Beginner' },
  { word: 'house', meaning: '집', example: 'This is my house.', level: 'Beginner' },
  { word: 'car', meaning: '차', example: 'He drives a car.', level: 'Beginner' },
  { word: 'tree', meaning: '나무', example: 'The tree is tall.', level: 'Beginner' },
  { word: 'flower', meaning: '꽃', example: 'I like this flower.', level: 'Beginner' },
  { word: 'sun', meaning: '태양', example: 'The sun is bright.', level: 'Beginner' },
  { word: 'moon', meaning: '달', example: 'The moon is beautiful.', level: 'Beginner' },
  { word: 'star', meaning: '별', example: 'I see a star.', level: 'Beginner' },
  { word: 'rain', meaning: '비', example: 'The rain is falling.', level: 'Beginner' },
  { word: 'snow', meaning: '눈', example: 'Snow is white.', level: 'Beginner' },
  { word: 'food', meaning: '음식', example: 'The food is delicious.', level: 'Beginner' },
  { word: 'milk', meaning: '우유', example: 'I drink milk.', level: 'Beginner' },
  { word: 'bread', meaning: '빵', example: 'I eat bread.', level: 'Beginner' },
  { word: 'rice', meaning: '쌀', example: 'We eat rice.', level: 'Beginner' },
  { word: 'fish', meaning: '물고기', example: 'I like fish.', level: 'Beginner' },
  { word: 'bird', meaning: '새', example: 'The bird sings.', level: 'Beginner' },
  { word: 'horse', meaning: '말', example: 'The horse runs fast.', level: 'Beginner' },
  { word: 'cow', meaning: '소', example: 'The cow eats grass.', level: 'Beginner' },
  { word: 'pig', meaning: '돼지', example: 'The pig is fat.', level: 'Beginner' },
  { word: 'sheep', meaning: '양', example: 'Sheep are white.', level: 'Beginner' },
  { word: 'table', meaning: '탁자', example: 'Put it on the table.', level: 'Beginner' },
  { word: 'chair', meaning: '의자', example: 'Sit on the chair.', level: 'Beginner' },
  { word: 'door', meaning: '문', example: 'Open the door.', level: 'Beginner' },
  { word: 'window', meaning: '창문', example: 'Close the window.', level: 'Beginner' },
  { word: 'bed', meaning: '침대', example: 'I sleep in bed.', level: 'Beginner' },
  { word: 'phone', meaning: '전화기', example: 'I use my phone.', level: 'Beginner' },
  { word: 'computer', meaning: '컴퓨터', example: 'I use a computer.', level: 'Beginner' },
  { word: 'music', meaning: '음악', example: 'I listen to music.', level: 'Beginner' },
  { word: 'game', meaning: '게임', example: 'Lets play a game.', level: 'Beginner' },
  { word: 'friend', meaning: '친구', example: 'She is my friend.', level: 'Beginner' },
  { word: 'family', meaning: '가족', example: 'I love my family.', level: 'Beginner' },
  { word: 'mother', meaning: '어머니', example: 'My mother is kind.', level: 'Beginner' },
  { word: 'father', meaning: '아버지', example: 'My father works.', level: 'Beginner' },
  { word: 'brother', meaning: '형제', example: 'I have a brother.', level: 'Beginner' },
  { word: 'sister', meaning: '자매', example: 'My sister is smart.', level: 'Beginner' },
  { word: 'baby', meaning: '아기', example: 'The baby is cute.', level: 'Beginner' },
  { word: 'name', meaning: '이름', example: 'What is your name?', level: 'Beginner' },
  { word: 'time', meaning: '시간', example: 'What time is it?', level: 'Beginner' },
  { word: 'day', meaning: '날', example: 'Its a nice day.', level: 'Beginner' },
  { word: 'night', meaning: '밤', example: 'Good night.', level: 'Beginner' },
  { word: 'morning', meaning: '아침', example: 'Good morning.', level: 'Beginner' },
  { word: 'evening', meaning: '저녁', example: 'Good evening.', level: 'Beginner' },
  { word: 'week', meaning: '주', example: 'See you next week.', level: 'Beginner' },
  { word: 'month', meaning: '달', example: 'January is a month.', level: 'Beginner' },
  { word: 'year', meaning: '년', example: 'Happy New Year.', level: 'Beginner' },
  { word: 'red', meaning: '빨간', example: 'The apple is red.', level: 'Beginner' },
  { word: 'blue', meaning: '파란', example: 'The sky is blue.', level: 'Beginner' },
  { word: 'green', meaning: '초록', example: 'The grass is green.', level: 'Beginner' },
  { word: 'yellow', meaning: '노란', example: 'The sun is yellow.', level: 'Beginner' },
  { word: 'black', meaning: '검은', example: 'The cat is black.', level: 'Beginner' },
  { word: 'white', meaning: '흰', example: 'Snow is white.', level: 'Beginner' },
  { word: 'big', meaning: '큰', example: 'The elephant is big.', level: 'Beginner' },
  { word: 'small', meaning: '작은', example: 'The ant is small.', level: 'Beginner' },
  { word: 'hot', meaning: '뜨거운', example: 'The tea is hot.', level: 'Beginner' },
  { word: 'cold', meaning: '추운', example: 'It is cold outside.', level: 'Beginner' },
  { word: 'happy', meaning: '행복한', example: 'I am happy.', level: 'Beginner' },
  { word: 'sad', meaning: '슬픈', example: 'Dont be sad.', level: 'Beginner' },
  { word: 'good', meaning: '좋은', example: 'This is good.', level: 'Beginner' },
  { word: 'bad', meaning: '나쁜', example: 'That is bad.', level: 'Beginner' },
  { word: 'new', meaning: '새로운', example: 'I have a new bike.', level: 'Beginner' },
  { word: 'old', meaning: '오래된', example: 'This house is old.', level: 'Beginner' },
  { word: 'run', meaning: '달리다', example: 'I can run fast.', level: 'Beginner' },
  { word: 'walk', meaning: '걷다', example: 'Lets walk together.', level: 'Beginner' },
  { word: 'eat', meaning: '먹다', example: 'I eat breakfast.', level: 'Beginner' },
  { word: 'drink', meaning: '마시다', example: 'I drink coffee.', level: 'Beginner' },
  { word: 'sleep', meaning: '자다', example: 'I sleep at night.', level: 'Beginner' },
  { word: 'play', meaning: '놀다', example: 'Children play outside.', level: 'Beginner' },
  { word: 'read', meaning: '읽다', example: 'I read books.', level: 'Beginner' },
  { word: 'write', meaning: '쓰다', example: 'I write a letter.', level: 'Beginner' },
  { word: 'sing', meaning: '노래하다', example: 'She can sing well.', level: 'Beginner' },
  { word: 'dance', meaning: '춤추다', example: 'Lets dance.', level: 'Beginner' },
  { word: 'swim', meaning: '수영하다', example: 'I can swim.', level: 'Beginner' },
  { word: 'fly', meaning: '날다', example: 'Birds can fly.', level: 'Beginner' },
  { word: 'jump', meaning: '뛰다', example: 'The rabbit can jump.', level: 'Beginner' },
  { word: 'sit', meaning: '앉다', example: 'Please sit down.', level: 'Beginner' },
  { word: 'stand', meaning: '서다', example: 'Stand up, please.', level: 'Beginner' },
  { word: 'open', meaning: '열다', example: 'Open your book.', level: 'Beginner' },
  { word: 'close', meaning: '닫다', example: 'Close the door.', level: 'Beginner' },
  { word: 'see', meaning: '보다', example: 'I can see you.', level: 'Beginner' },
  { word: 'hear', meaning: '듣다', example: 'I hear music.', level: 'Beginner' },
  { word: 'smell', meaning: '냄새 맡다', example: 'I smell flowers.', level: 'Beginner' },
  { word: 'taste', meaning: '맛보다', example: 'Taste this food.', level: 'Beginner' },
  { word: 'think', meaning: '생각하다', example: 'I think so.', level: 'Beginner' },
  { word: 'know', meaning: '알다', example: 'I know the answer.', level: 'Beginner' },
  { word: 'love', meaning: '사랑하다', example: 'I love you.', level: 'Beginner' },
  { word: 'like', meaning: '좋아하다', example: 'I like pizza.', level: 'Beginner' },
  { word: 'want', meaning: '원하다', example: 'I want water.', level: 'Beginner' },
  { word: 'need', meaning: '필요하다', example: 'I need help.', level: 'Beginner' },
  { word: 'give', meaning: '주다', example: 'Give me that.', level: 'Beginner' },
  { word: 'take', meaning: '가져가다', example: 'Take this with you.', level: 'Beginner' },
  { word: 'make', meaning: '만들다', example: 'I make a cake.', level: 'Beginner' },
  { word: 'help', meaning: '돕다', example: 'Please help me.', level: 'Beginner' },
  { word: 'work', meaning: '일하다', example: 'I work hard.', level: 'Beginner' },
  { word: 'study', meaning: '공부하다', example: 'I study English.', level: 'Beginner' },

  // 🟡 2. Middle School (중등필수단어 1500) - 100 words
  { word: 'develop', meaning: '발전하다', example: 'We develop skills.', level: 'Middle School' },
  { word: 'improve', meaning: '향상시키다', example: 'Improve your English.', level: 'Middle School' },
  { word: 'create', meaning: '창조하다', example: 'I create music.', level: 'Middle School' },
  { word: 'environment', meaning: '환경', example: 'Protect the environment.', level: 'Middle School' },
  { word: 'decision', meaning: '결정', example: 'Make a decision.', level: 'Middle School' },
  { word: 'experience', meaning: '경험', example: 'I have experience.', level: 'Middle School' },
  { word: 'education', meaning: '교육', example: 'Education is important.', level: 'Middle School' },
  { word: 'information', meaning: '정보', example: 'I need information.', level: 'Middle School' },
  { word: 'communication', meaning: '의사소통', example: 'Communication is key.', level: 'Middle School' },
  { word: 'technology', meaning: '기술', example: 'Technology advances quickly.', level: 'Middle School' },
  { word: 'population', meaning: '인구', example: 'The population is growing.', level: 'Middle School' },
  { word: 'government', meaning: '정부', example: 'The government makes laws.', level: 'Middle School' },
  { word: 'society', meaning: '사회', example: 'We live in a society.', level: 'Middle School' },
  { word: 'culture', meaning: '문화', example: 'Korean culture is rich.', level: 'Middle School' },
  { word: 'tradition', meaning: '전통', example: 'This is our tradition.', level: 'Middle School' },
  { word: 'knowledge', meaning: '지식', example: 'Knowledge is power.', level: 'Middle School' },
  { word: 'opportunity', meaning: '기회', example: 'This is a great opportunity.', level: 'Middle School' },
  { word: 'relationship', meaning: '관계', example: 'We have a good relationship.', level: 'Middle School' },
  { word: 'community', meaning: '공동체', example: 'Help the community.', level: 'Middle School' },
  { word: 'individual', meaning: '개인', example: 'Each individual matters.', level: 'Middle School' },
  { word: 'purpose', meaning: '목적', example: 'What is the purpose?', level: 'Middle School' },
  { word: 'attitude', meaning: '태도', example: 'Your attitude is positive.', level: 'Middle School' },
  { word: 'behavior', meaning: '행동', example: 'Good behavior is expected.', level: 'Middle School' },
  { word: 'influence', meaning: '영향', example: 'Media has influence.', level: 'Middle School' },
  { word: 'achievement', meaning: '성취', example: 'Its a great achievement.', level: 'Middle School' },
  { word: 'difference', meaning: '차이', example: 'There is a difference.', level: 'Middle School' },
  { word: 'condition', meaning: '조건', example: 'Under one condition.', level: 'Middle School' },
  { word: 'process', meaning: '과정', example: 'It takes a process.', level: 'Middle School' },
  { word: 'method', meaning: '방법', example: 'Try this method.', level: 'Middle School' },
  { word: 'solution', meaning: '해결책', example: 'Find a solution.', level: 'Middle School' },
  { word: 'result', meaning: '결과', example: 'The result was good.', level: 'Middle School' },
  { word: 'effort', meaning: '노력', example: 'Effort is required.', level: 'Middle School' },
  { word: 'ability', meaning: '능력', example: 'She has great ability.', level: 'Middle School' },
  { word: 'skill', meaning: '기술', example: 'Develop your skills.', level: 'Middle School' },
  { word: 'confidence', meaning: '자신감', example: 'Have confidence.', level: 'Middle School' },
  { word: 'courage', meaning: '용기', example: 'Take courage.', level: 'Middle School' },
  { word: 'patience', meaning: '인내', example: 'Patience is important.', level: 'Middle School' },
  { word: 'respect', meaning: '존경', example: 'Show respect.', level: 'Middle School' },
  { word: 'responsibility', meaning: '책임', example: 'Its your responsibility.', level: 'Middle School' },
  { word: 'honesty', meaning: '정직', example: 'Honesty is best.', level: 'Middle School' },
  { word: 'freedom', meaning: '자유', example: 'Freedom is precious.', level: 'Middle School' },
  { word: 'justice', meaning: '정의', example: 'Fight for justice.', level: 'Middle School' },
  { word: 'peace', meaning: '평화', example: 'We want peace.', level: 'Middle School' },
  { word: 'nature', meaning: '자연', example: 'Love nature.', level: 'Middle School' },
  { word: 'energy', meaning: '에너지', example: 'Save energy.', level: 'Middle School' },
  { word: 'climate', meaning: '기후', example: 'Climate is changing.', level: 'Middle School' },
  { word: 'pollution', meaning: '오염', example: 'Stop pollution.', level: 'Middle School' },
  { word: 'resource', meaning: '자원', example: 'Use resources wisely.', level: 'Middle School' },
  { word: 'industry', meaning: '산업', example: 'Industry is growing.', level: 'Middle School' },
  { word: 'economy', meaning: '경제', example: 'The economy is stable.', level: 'Middle School' },
  { word: 'business', meaning: '사업', example: 'Start a business.', level: 'Middle School' },
  { word: 'product', meaning: '제품', example: 'This product is new.', level: 'Middle School' },
  { word: 'service', meaning: '서비스', example: 'Good service here.', level: 'Middle School' },
  { word: 'quality', meaning: '품질', example: 'Quality matters.', level: 'Middle School' },
  { word: 'value', meaning: '가치', example: 'What is its value?', level: 'Middle School' },
  { word: 'advantage', meaning: '이점', example: 'Theres an advantage.', level: 'Middle School' },
  { word: 'disadvantage', meaning: '불리', example: 'It has a disadvantage.', level: 'Middle School' },
  { word: 'benefit', meaning: '이익', example: 'It will benefit you.', level: 'Middle School' },
  { word: 'challenge', meaning: '도전', example: 'Face the challenge.', level: 'Middle School' },
  { word: 'competition', meaning: '경쟁', example: 'Competition is fierce.', level: 'Middle School' },
  { word: 'strategy', meaning: '전략', example: 'Plan a strategy.', level: 'Middle School' },
  { word: 'goal', meaning: '목표', example: 'Set a goal.', level: 'Middle School' },
  { word: 'progress', meaning: '진전', example: 'Making progress.', level: 'Middle School' },
  { word: 'success', meaning: '성공', example: 'Success is near.', level: 'Middle School' },
  { word: 'failure', meaning: '실패', example: 'Learn from failure.', level: 'Middle School' },
  { word: 'mistake', meaning: '실수', example: 'Everyone makes mistakes.', level: 'Middle School' },
  { word: 'opportunity', meaning: '기회', example: 'Seize the opportunity.', level: 'Middle School' },
  { word: 'discovery', meaning: '발견', example: 'A new discovery.', level: 'Middle School' },
  { word: 'invention', meaning: '발명', example: 'Great invention.', level: 'Middle School' },
  { word: 'imagination', meaning: '상상력', example: 'Use your imagination.', level: 'Middle School' },
  { word: 'creativity', meaning: '창의성', example: 'Creativity is key.', level: 'Middle School' },
  { word: 'expression', meaning: '표현', example: 'Freedom of expression.', level: 'Middle School' },
  { word: 'emotion', meaning: '감정', example: 'Control your emotions.', level: 'Middle School' },
  { word: 'memory', meaning: '기억', example: 'A happy memory.', level: 'Middle School' },
  { word: 'attention', meaning: '주의', example: 'Pay attention.', level: 'Middle School' },
  { word: 'opinion', meaning: '의견', example: 'Share your opinion.', level: 'Middle School' },
  { word: 'argument', meaning: '논쟁', example: 'A strong argument.', level: 'Middle School' },
  { word: 'evidence', meaning: '증거', example: 'Show the evidence.', level: 'Middle School' },
  { word: 'research', meaning: '연구', example: 'Do research.', level: 'Middle School' },
  { word: 'experiment', meaning: '실험', example: 'Conduct an experiment.', level: 'Middle School' },
  { word: 'observation', meaning: '관찰', example: 'Through observation.', level: 'Middle School' },
  { word: 'conclusion', meaning: '결론', example: 'Draw a conclusion.', level: 'Middle School' },
  { word: 'explanation', meaning: '설명', example: 'Give an explanation.', level: 'Middle School' },
  { word: 'description', meaning: '묘사', example: 'A detailed description.', level: 'Middle School' },
  { word: 'introduction', meaning: '소개', example: 'A brief introduction.', level: 'Middle School' },
  { word: 'summary', meaning: '요약', example: 'Write a summary.', level: 'Middle School' },
  { word: 'detail', meaning: '세부사항', example: 'Check the details.', level: 'Middle School' },
  { word: 'example', meaning: '예', example: 'Give an example.', level: 'Middle School' },
  { word: 'characteristic', meaning: '특징', example: 'Key characteristic.', level: 'Middle School' },
  { word: 'similarity', meaning: '유사점', example: 'Find similarities.', level: 'Middle School' },
  { word: 'possibility', meaning: '가능성', example: 'Theres a possibility.', level: 'Middle School' },
  { word: 'difficulty', meaning: '어려움', example: 'Face difficulties.', level: 'Middle School' },
  { word: 'situation', meaning: '상황', example: 'In this situation.', level: 'Middle School' },
  { word: 'circumstance', meaning: '상황', example: 'Under the circumstances.', level: 'Middle School' },
  { word: 'consequence', meaning: '결과', example: 'Face the consequences.', level: 'Middle School' },
  { word: 'reaction', meaning: '반응', example: 'A quick reaction.', level: 'Middle School' },
  { word: 'impression', meaning: '인상', example: 'A good impression.', level: 'Middle School' },
  { word: 'preparation', meaning: '준비', example: 'Preparation is key.', level: 'Middle School' },
  { word: 'protection', meaning: '보호', example: 'Under protection.', level: 'Middle School' },
  { word: 'organization', meaning: '조직', example: 'Join an organization.', level: 'Middle School' },
  { word: 'celebration', meaning: '축하', example: 'A big celebration.', level: 'Middle School' },

  // 🔵 3. High School Basic - 100 words
  { word: 'analyze', meaning: '분석하다', example: 'Analyze the data.', level: 'High School Basic' },
  { word: 'structure', meaning: '구조', example: 'The structure is strong.', level: 'High School Basic' },
  { word: 'theory', meaning: '이론', example: 'This is a theory.', level: 'High School Basic' },
  { word: 'concept', meaning: '개념', example: 'Understand the concept.', level: 'High School Basic' },
  { word: 'function', meaning: '기능', example: 'Each function is useful.', level: 'High School Basic' },
  { word: 'principle', meaning: '원리', example: 'Basic principle.', level: 'High School Basic' },
  { word: 'hypothesis', meaning: '가설', example: 'Test the hypothesis.', level: 'High School Basic' },
  { word: 'phenomenon', meaning: '현상', example: 'Natural phenomenon.', level: 'High School Basic' },
  { word: 'mechanism', meaning: '메커니즘', example: 'The mechanism works.', level: 'High School Basic' },
  { word: 'component', meaning: '구성요소', example: 'Key component.', level: 'High School Basic' },
  { word: 'perspective', meaning: '관점', example: 'From my perspective.', level: 'High School Basic' },
  { word: 'interpretation', meaning: '해석', example: 'My interpretation.', level: 'High School Basic' },
  { word: 'philosophy', meaning: '철학', example: 'A philosophy of life.', level: 'High School Basic' },
  { word: 'ideology', meaning: '이념', example: 'Political ideology.', level: 'High School Basic' },
  { word: 'doctrine', meaning: '교리', example: 'Religious doctrine.', level: 'High School Basic' },
  { word: 'paradigm', meaning: '패러다임', example: 'A new paradigm.', level: 'High School Basic' },
  { word: 'framework', meaning: '틀', example: 'Within the framework.', level: 'High School Basic' },
  { word: 'context', meaning: '맥락', example: 'In this context.', level: 'High School Basic' },
  { word: 'abstract', meaning: '추상적인', example: 'Abstract idea.', level: 'High School Basic' },
  { word: 'concrete', meaning: '구체적인', example: 'Concrete example.', level: 'High School Basic' },
  { word: 'rational', meaning: '합리적인', example: 'Rational thinking.', level: 'High School Basic' },
  { word: 'empirical', meaning: '경험적인', example: 'Empirical evidence.', level: 'High School Basic' },
  { word: 'theoretical', meaning: '이론적인', example: 'Theoretical approach.', level: 'High School Basic' },
  { word: 'practical', meaning: '실용적인', example: 'Practical application.', level: 'High School Basic' },
  { word: 'fundamental', meaning: '근본적인', example: 'Fundamental right.', level: 'High School Basic' },
  { word: 'essential', meaning: '필수적인', example: 'Essential element.', level: 'High School Basic' },
  { word: 'significant', meaning: '중요한', example: 'Significant change.', level: 'High School Basic' },
  { word: 'crucial', meaning: '결정적인', example: 'Crucial moment.', level: 'High School Basic' },
  { word: 'critical', meaning: '비판적인', example: 'Critical thinking.', level: 'High School Basic' },
  { word: 'inevitable', meaning: '불가피한', example: 'Inevitable result.', level: 'High School Basic' },
  { word: 'potential', meaning: '잠재적인', example: 'Potential risk.', level: 'High School Basic' },
  { word: 'contemporary', meaning: '현대의', example: 'Contemporary art.', level: 'High School Basic' },
  { word: 'conventional', meaning: '전통적인', example: 'Conventional wisdom.', level: 'High School Basic' },
  { word: 'alternative', meaning: '대안의', example: 'Alternative solution.', level: 'High School Basic' },
  { word: 'sufficient', meaning: '충분한', example: 'Sufficient evidence.', level: 'High School Basic' },
  { word: 'adequate', meaning: '적절한', example: 'Adequate preparation.', level: 'High School Basic' },
  { word: 'appropriate', meaning: '적합한', example: 'Appropriate behavior.', level: 'High School Basic' },
  { word: 'relevant', meaning: '관련된', example: 'Relevant information.', level: 'High School Basic' },
  { word: 'efficient', meaning: '효율적인', example: 'Efficient method.', level: 'High School Basic' },
  { word: 'effective', meaning: '효과적인', example: 'Effective strategy.', level: 'High School Basic' },
  { word: 'consistent', meaning: '일관된', example: 'Consistent effort.', level: 'High School Basic' },
  { word: 'comprehensive', meaning: '포괄적인', example: 'Comprehensive review.', level: 'High School Basic' },
  { word: 'extensive', meaning: '광범위한', example: 'Extensive research.', level: 'High School Basic' },
  { word: 'intensive', meaning: '집중적인', example: 'Intensive training.', level: 'High School Basic' },
  { word: 'diverse', meaning: '다양한', example: 'Diverse opinions.', level: 'High School Basic' },
  { word: 'predominant', meaning: '지배적인', example: 'Predominant view.', level: 'High School Basic' },
  { word: 'dominant', meaning: '우세한', example: 'Dominant position.', level: 'High School Basic' },
  { word: 'prominent', meaning: '저명한', example: 'Prominent figure.', level: 'High School Basic' },
  { word: 'distinct', meaning: '뚜렷한', example: 'Distinct feature.', level: 'High School Basic' },
  { word: 'unique', meaning: '독특한', example: 'Unique opportunity.', level: 'High School Basic' },
  { word: 'elaborate', meaning: '정교한', example: 'Elaborate plan.', level: 'High School Basic' },
  { word: 'sophisticated', meaning: '정교한', example: 'Sophisticated system.', level: 'High School Basic' },
  { word: 'complex', meaning: '복잡한', example: 'Complex problem.', level: 'High School Basic' },
  { word: 'complicated', meaning: '복잡한', example: 'Complicated situation.', level: 'High School Basic' },
  { word: 'controversial', meaning: '논란이 되는', example: 'Controversial issue.', level: 'High School Basic' },
  { word: 'ambiguous', meaning: '모호한', example: 'Ambiguous statement.', level: 'High School Basic' },
  { word: 'explicit', meaning: '명백한', example: 'Explicit instruction.', level: 'High School Basic' },
  { word: 'implicit', meaning: '암시적인', example: 'Implicit meaning.', level: 'High School Basic' },
  { word: 'inevitable', meaning: '불가피한', example: 'Inevitable consequence.', level: 'High School Basic' },
  { word: 'spontaneous', meaning: '자발적인', example: 'Spontaneous reaction.', level: 'High School Basic' },
  { word: 'deliberate', meaning: '고의적인', example: 'Deliberate action.', level: 'High School Basic' },
  { word: 'voluntary', meaning: '자발적인', example: 'Voluntary work.', level: 'High School Basic' },
  { word: 'mandatory', meaning: '의무적인', example: 'Mandatory course.', level: 'High School Basic' },
  { word: 'compulsory', meaning: '강제적인', example: 'Compulsory education.', level: 'High School Basic' },
  { word: 'legitimate', meaning: '합법적인', example: 'Legitimate right.', level: 'High School Basic' },
  { word: 'valid', meaning: '유효한', example: 'Valid argument.', level: 'High School Basic' },
  { word: 'plausible', meaning: '그럴듯한', example: 'Plausible explanation.', level: 'High School Basic' },
  { word: 'feasible', meaning: '실현 가능한', example: 'Feasible plan.', level: 'High School Basic' },
  { word: 'viable', meaning: '실행 가능한', example: 'Viable option.', level: 'High School Basic' },
  { word: 'sustainable', meaning: '지속 가능한', example: 'Sustainable development.', level: 'High School Basic' },
  { word: 'tangible', meaning: '유형의', example: 'Tangible results.', level: 'High School Basic' },
  { word: 'intrinsic', meaning: '본질적인', example: 'Intrinsic value.', level: 'High School Basic' },
  { word: 'inherent', meaning: '내재된', example: 'Inherent risk.', level: 'High School Basic' },
  { word: 'integral', meaning: '필수적인', example: 'Integral part.', level: 'High School Basic' },
  { word: 'preliminary', meaning: '예비의', example: 'Preliminary results.', level: 'High School Basic' },
  { word: 'tentative', meaning: '잠정적인', example: 'Tentative agreement.', level: 'High School Basic' },
  { word: 'provisional', meaning: '임시의', example: 'Provisional measure.', level: 'High School Basic' },
  { word: 'interim', meaning: '중간의', example: 'Interim report.', level: 'High School Basic' },
  { word: 'subsequent', meaning: '이후의', example: 'Subsequent events.', level: 'High School Basic' },
  { word: 'ultimate', meaning: '궁극적인', example: 'Ultimate goal.', level: 'High School Basic' },
  { word: 'cumulative', meaning: '누적되는', example: 'Cumulative effect.', level: 'High School Basic' },
  { word: 'gradual', meaning: '점진적인', example: 'Gradual improvement.', level: 'High School Basic' },
  { word: 'simultaneous', meaning: '동시의', example: 'Simultaneous translation.', level: 'High School Basic' },
  { word: 'intermittent', meaning: '간헐적인', example: 'Intermittent rain.', level: 'High School Basic' },
  { word: 'persistent', meaning: '지속적인', example: 'Persistent effort.', level: 'High School Basic' },
  { word: 'constant', meaning: '지속적인', example: 'Constant change.', level: 'High School Basic' },
  { word: 'perpetual', meaning: '영구적인', example: 'Perpetual motion.', level: 'High School Basic' },
  { word: 'transient', meaning: '일시적인', example: 'Transient phenomenon.', level: 'High School Basic' },
  { word: 'temporary', meaning: '일시적인', example: 'Temporary solution.', level: 'High School Basic' },
  { word: 'permanent', meaning: '영구적인', example: 'Permanent damage.', level: 'High School Basic' },
  { word: 'durable', meaning: '내구성 있는', example: 'Durable material.', level: 'High School Basic' },
  { word: 'fragile', meaning: '취약한', example: 'Fragile ecosystem.', level: 'High School Basic' },
  { word: 'resilient', meaning: '회복력 있는', example: 'Resilient economy.', level: 'High School Basic' },
  { word: 'adaptable', meaning: '적응력 있는', example: 'Adaptable species.', level: 'High School Basic' },
  { word: 'versatile', meaning: '다재다능한', example: 'Versatile tool.', level: 'High School Basic' },
  { word: 'dynamic', meaning: '역동적인', example: 'Dynamic process.', level: 'High School Basic' },
  { word: 'static', meaning: '정적인', example: 'Static situation.', level: 'High School Basic' },
  { word: 'stable', meaning: '안정된', example: 'Stable environment.', level: 'High School Basic' },
  { word: 'unprecedented', meaning: '전례 없는', example: 'Unprecedented event.', level: 'High School Basic' },

  // 🔴 4. CSAT Level (수능 2000) - 100 words
  { word: 'notwithstanding', meaning: '그럼에도 불구하고', example: 'Notwithstanding difficulties, he succeeded.', level: 'CSAT Level' },
  { word: 'substantial', meaning: '상당한', example: 'There is substantial evidence.', level: 'CSAT Level' },
  { word: 'alleviate', meaning: '완화하다', example: 'Medicine can alleviate pain.', level: 'CSAT Level' },
  { word: 'meticulous', meaning: '꼼꼼한', example: 'She is meticulous in work.', level: 'CSAT Level' },
  { word: 'implication', meaning: '함의', example: 'We must consider the implication.', level: 'CSAT Level' },
  { word: 'prerequisite', meaning: '전제조건', example: 'This is a prerequisite.', level: 'CSAT Level' },
  { word: 'ubiquitous', meaning: '어디에나 있는', example: 'Smartphones are ubiquitous.', level: 'CSAT Level' },
  { word: 'conspicuous', meaning: '두드러진', example: 'Conspicuous consumption.', level: 'CSAT Level' },
  { word: 'imperative', meaning: '필수적인', example: 'It is imperative to act.', level: 'CSAT Level' },
  { word: 'unprecedented', meaning: '전례 없는', example: 'Unprecedented scale.', level: 'CSAT Level' },
  { word: 'inevitable', meaning: '불가피한', example: 'Change is inevitable.', level: 'CSAT Level' },
  { word: 'paradoxical', meaning: '역설적인', example: 'Paradoxical situation.', level: 'CSAT Level' },
  { word: 'ambiguous', meaning: '모호한', example: 'Ambiguous answer.', level: 'CSAT Level' },
  { word: 'obscure', meaning: '불분명한', example: 'Obscure reference.', level: 'CSAT Level' },
  { word: 'obsolete', meaning: '시대에 뒤진', example: 'Obsolete technology.', level: 'CSAT Level' },
  { word: 'archaic', meaning: '고풍의', example: 'Archaic language.', level: 'CSAT Level' },
  { word: 'rudimentary', meaning: '기초적인', example: 'Rudimentary knowledge.', level: 'CSAT Level' },
  { word: 'elementary', meaning: '초보의', example: 'Elementary mistake.', level: 'CSAT Level' },
  { word: 'profound', meaning: '심오한', example: 'Profound insight.', level: 'CSAT Level' },
  { word: 'superficial', meaning: '피상적인', example: 'Superficial understanding.', level: 'CSAT Level' },
  { word: 'trivial', meaning: '사소한', example: 'Trivial matter.', level: 'CSAT Level' },
  { word: 'negligible', meaning: '무시해도 될', example: 'Negligible amount.', level: 'CSAT Level' },
  { word: 'substantive', meaning: '실질적인', example: 'Substantive changes.', level: 'CSAT Level' },
  { word: 'intrinsic', meaning: '본질적인', example: 'Intrinsic nature.', level: 'CSAT Level' },
  { word: 'extrinsic', meaning: '외부의', example: 'Extrinsic factors.', level: 'CSAT Level' },
  { word: 'innate', meaning: '타고난', example: 'Innate ability.', level: 'CSAT Level' },
  { word: 'acquired', meaning: '후천적인', example: 'Acquired skill.', level: 'CSAT Level' },
  { word: 'hereditary', meaning: '유전적인', example: 'Hereditary trait.', level: 'CSAT Level' },
  { word: 'congenital', meaning: '선천적인', example: 'Congenital condition.', level: 'CSAT Level' },
  { word: 'chronic', meaning: '만성적인', example: 'Chronic disease.', level: 'CSAT Level' },
  { word: 'acute', meaning: '급성의', example: 'Acute problem.', level: 'CSAT Level' },
  { word: 'latent', meaning: '잠재된', example: 'Latent talent.', level: 'CSAT Level' },
  { word: 'dormant', meaning: '휴면 상태의', example: 'Dormant volcano.', level: 'CSAT Level' },
  { word: 'manifest', meaning: '명백한', example: 'Manifest destiny.', level: 'CSAT Level' },
  { word: 'lucid', meaning: '명쾌한', example: 'Lucid explanation.', level: 'CSAT Level' },
  { word: 'coherent', meaning: '일관된', example: 'Coherent argument.', level: 'CSAT Level' },
  { word: 'articulate', meaning: '분명한', example: 'Articulate speaker.', level: 'CSAT Level' },
  { word: 'eloquent', meaning: '웅변적인', example: 'Eloquent speech.', level: 'CSAT Level' },
  { word: 'cogent', meaning: '설득력 있는', example: 'Cogent reasoning.', level: 'CSAT Level' },
  { word: 'compelling', meaning: '강력한', example: 'Compelling evidence.', level: 'CSAT Level' },
  { word: 'stringent', meaning: '엄격한', example: 'Stringent rules.', level: 'CSAT Level' },
  { word: 'rigorous', meaning: '엄밀한', example: 'Rigorous analysis.', level: 'CSAT Level' },
  { word: 'scrupulous', meaning: '세심한', example: 'Scrupulous attention.', level: 'CSAT Level' },
  { word: 'diligent', meaning: '부지런한', example: 'Diligent worker.', level: 'CSAT Level' },
  { word: 'assiduous', meaning: '근면한', example: 'Assiduous study.', level: 'CSAT Level' },
  { word: 'tenacious', meaning: '집요한', example: 'Tenacious grip.', level: 'CSAT Level' },
  { word: 'indefatigable', meaning: '지칠 줄 모르는', example: 'Indefatigable spirit.', level: 'CSAT Level' },
  { word: 'resilient', meaning: '회복력 있는', example: 'Resilient character.', level: 'CSAT Level' },
  { word: 'robust', meaning: '튼튼한', example: 'Robust system.', level: 'CSAT Level' },
  { word: 'vigorous', meaning: '활기찬', example: 'Vigorous exercise.', level: 'CSAT Level' },
  { word: 'strenuous', meaning: '격렬한', example: 'Strenuous effort.', level: 'CSAT Level' },
  { word: 'arduous', meaning: '힘든', example: 'Arduous journey.', level: 'CSAT Level' },
  { word: 'onerous', meaning: '부담스러운', example: 'Onerous task.', level: 'CSAT Level' },
  { word: 'formidable', meaning: '어마어마한', example: 'Formidable challenge.', level: 'CSAT Level' },
  { word: 'daunting', meaning: '위압적인', example: 'Daunting prospect.', level: 'CSAT Level' },
  { word: 'ominous', meaning: '불길한', example: 'Ominous sign.', level: 'CSAT Level' },
  { word: 'sinister', meaning: '사악한', example: 'Sinister motive.', level: 'CSAT Level' },
  { word: 'malevolent', meaning: '악의적인', example: 'Malevolent intent.', level: 'CSAT Level' },
  { word: 'benevolent', meaning: '자비로운', example: 'Benevolent dictator.', level: 'CSAT Level' },
  { word: 'altruistic', meaning: '이타적인', example: 'Altruistic behavior.', level: 'CSAT Level' },
  { word: 'philanthropic', meaning: '박애의', example: 'Philanthropic work.', level: 'CSAT Level' },
  { word: 'magnanimous', meaning: '도량이 넓은', example: 'Magnanimous gesture.', level: 'CSAT Level' },
  { word: 'munificent', meaning: '인색하지 않은', example: 'Munificent donation.', level: 'CSAT Level' },
  { word: 'lavish', meaning: '풍성한', example: 'Lavish spending.', level: 'CSAT Level' },
  { word: 'extravagant', meaning: '낭비적인', example: 'Extravagant lifestyle.', level: 'CSAT Level' },
  { word: 'frugal', meaning: '검소한', example: 'Frugal habits.', level: 'CSAT Level' },
  { word: 'austere', meaning: '엄격한', example: 'Austere life.', level: 'CSAT Level' },
  { word: 'spartan', meaning: '간소한', example: 'Spartan conditions.', level: 'CSAT Level' },
  { word: 'opulent', meaning: '호화로운', example: 'Opulent palace.', level: 'CSAT Level' },
  { word: 'sumptuous', meaning: '화려한', example: 'Sumptuous feast.', level: 'CSAT Level' },
  { word: 'ostentatious', meaning: '과시적인', example: 'Ostentatious display.', level: 'CSAT Level' },
  { word: 'pretentious', meaning: '가식적인', example: 'Pretentious attitude.', level: 'CSAT Level' },
  { word: 'pompous', meaning: '거드름 피우는', example: 'Pompous official.', level: 'CSAT Level' },
  { word: 'haughty', meaning: '거만한', example: 'Haughty manner.', level: 'CSAT Level' },
  { word: 'arrogant', meaning: '오만한', example: 'Arrogant behavior.', level: 'CSAT Level' },
  { word: 'condescending', meaning: '잘난 체하는', example: 'Condescending tone.', level: 'CSAT Level' },
  { word: 'disdainful', meaning: '경멸하는', example: 'Disdainful look.', level: 'CSAT Level' },
  { word: 'contemptuous', meaning: '멸시하는', example: 'Contemptuous remark.', level: 'CSAT Level' },
  { word: 'derisive', meaning: '비웃는', example: 'Derisive laughter.', level: 'CSAT Level' },
  { word: 'sardonic', meaning: '냉소적인', example: 'Sardonic smile.', level: 'CSAT Level' },
  { word: 'cynical', meaning: '냉소적인', example: 'Cynical view.', level: 'CSAT Level' },
  { word: 'skeptical', meaning: '회의적인', example: 'Skeptical approach.', level: 'CSAT Level' },
  { word: 'incredulous', meaning: '믿지 않는', example: 'Incredulous stare.', level: 'CSAT Level' },
  { word: 'dubious', meaning: '의심스러운', example: 'Dubious claim.', level: 'CSAT Level' },
  { word: 'equivocal', meaning: '모호한', example: 'Equivocal response.', level: 'CSAT Level' },
  { word: 'candid', meaning: '솔직한', example: 'Candid opinion.', level: 'CSAT Level' },
  { word: 'forthright', meaning: '직설적인', example: 'Forthright answer.', level: 'CSAT Level' },
  { word: 'blunt', meaning: '무뚝뚝한', example: 'Blunt statement.', level: 'CSAT Level' },
  { word: 'tactful', meaning: '재치있는', example: 'Tactful approach.', level: 'CSAT Level' },
  { word: 'diplomatic', meaning: '외교적인', example: 'Diplomatic answer.', level: 'CSAT Level' },
  { word: 'prudent', meaning: '신중한', example: 'Prudent decision.', level: 'CSAT Level' },
  { word: 'judicious', meaning: '현명한', example: 'Judicious choice.', level: 'CSAT Level' },
  { word: 'sagacious', meaning: '혜안의', example: 'Sagacious leader.', level: 'CSAT Level' },
  { word: 'astute', meaning: '기민한', example: 'Astute observer.', level: 'CSAT Level' },
  { word: 'shrewd', meaning: '빈틈없는', example: 'Shrewd businessman.', level: 'CSAT Level' },
  { word: 'perceptive', meaning: '통찰력 있는', example: 'Perceptive analysis.', level: 'CSAT Level' },
  { word: 'discerning', meaning: '식별력 있는', example: 'Discerning taste.', level: 'CSAT Level' },
  { word: 'pragmatic', meaning: '실용적인', example: 'Pragmatic approach.', level: 'CSAT Level' },
  { word: 'expedient', meaning: '편의의', example: 'Expedient measure.', level: 'CSAT Level' },
  { word: 'opportune', meaning: '때마침의', example: 'Opportune moment.', level: 'CSAT Level' }
];

    await Vocabulary.insertMany(vocabulary);
    console.log('✅ 10 Vocabulary words added for Beginner level');

    console.log('');
    console.log('🎉 Seed data created successfully!');
    console.log('--------------------------------');
    console.log('📧 Teacher: teacher@classcard.com');
    console.log('🔑 Password: password123');
    console.log('📧 Student: student@classcard.com');
    console.log('🔑 Password: password123');
    console.log('--------------------------------');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  }
};

seedData();